[build]
  publish = "public"
  command = "npm run build:css && cd functions && npm i && cd .. && gatsby build"
  functions = "functions"
[build.environment]
  NODE_VERSION = "12.13.0"
  YARN_VERSION = "1.19.1"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"